x = str(input("type a random word: "))
x = x.lower()
a = x.count("a")
e = x.count("e")
i = x.count("i")
ı = x.count("ı")
o = x.count("o")
ö = x.count("ö")
u = x.count("u")
ü = x.count("ü")

ans1 = (a + e + i + ı + o + ö + u + ü)
print(ans1)